### PR TITLE
updates server and languages compatibility

### PR DESCRIPTION
**Pull request by terakilobyte**
This resolves DOCSP-17219 and updates the language and server compatibility
for Node driver v4, dropping listed support for Node versions < 12 and
adding support for MongoDB 5.0.

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-17219

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17219/compatibility/

### Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Does it render on staging correctly?
- [x] Are all the links working?
- [x] Are the staging links in the PR description updated?

### CODE REVIEW

**Review by kyuan-mongodb — APPROVED** [review]
LGTM!

**Comment by terakilobyte** [comment]
@nbbeeken @emadum Could you review for accuracy?

**Comment by nbbeeken** [comment]
Looks good, the full set of 5.0 features is going to require users to enable the `useUnifiedTopology` flag in the 3.7+ driver version. Is there a kind of asterisk or hover text that can call that out?

**Comment by terakilobyte** [comment]
We can call it out in a note, and will definitely add it to the what's new/changelog. Does that work?

**Comment by nbbeeken** [comment]
SGTM, Thanks!

**Review by emadum — APPROVED** [review]
LGTM 👍

**Pull request merged**
