### PR TITLE
DOCSP-17266 compatibility tables update

### PR DESCRIPTION
**Pull request by kyuan-mongodb**
## Pull Request Info
Added 3.7 to both compatibility tables
Added MongoDB 5.0

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-17266

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-17266-CompatabilityTablesUpdate/compatibility/

### Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Does it render on staging correctly?
- [x] Are all the links working?
- [x] Are the staging links in the PR description updated?

### CODE REVIEW

**Review by terakilobyte — CHANGES_REQUESTED** [review]
LGTM, but let's add Node 16.x to the language list since it is the "current" version

**Review by terakilobyte — APPROVED** [review]

**Comment by kyuan-mongodb** [comment]
Hi @nbbeeken or @emadum, I  want to verify this is correct

**Review by nbbeeken — COMMENTED** [review]
It's accurate-ish, 3.7 will require the `useUnifiedTopology` flag to be true for certain features. If it is possible we should add an asterisk that calls that out.

**Review by nbbeeken — APPROVED** [review]
LGTM

**Pull request merged**
